services:
  # Среда
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/OrderProcessingApp
    command: sleep infinity
    depends_on:
      - postgres-order
      - postgres-payment
      - kafka
    networks:
      - microservices-net
    ports:
      - "5000-5002:5000-5002"

  # Заказы
  orderservice:
    build:
      context: ./OrderService
      dockerfile: DockerFile
    container_name: orderservice
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-order;Database=orderdb;Username=postgres;Password=postgres
      - PaymentService__BaseUrl=http://paymentservice:8080
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      postgres-order:
        condition: service_healthy
      paymentservice:
        condition: service_started
    networks:
      - microservices-net
    restart: unless-stopped

  # Платежи
  paymentservice:
    build:
      context: ./PaymentService
      dockerfile: DockerFile
    container_name: paymentservice
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres-payment;Database=paymentdb;Username=postgres;Password=postgres
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__Topics__PaymentEvents=payment-events
    depends_on:
      postgres-payment:
        condition: service_healthy
    networks:
      - microservices-net
    restart: unless-stopped

  # Бд OrderService
  postgres-order:
    image: postgres:15
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Бд PaymentService
  postgres-payment:
    image: postgres:15
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Брокер сообщений
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"     # для подключения с хоста (Postman, CLI)
      - "9093:9093"     # для внутренних подключений (микросервисы)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_KRAFT_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_order_data:
  postgres_payment_data:
  kafka_data:

networks:
  microservices-net:
    driver: bridge